### ISSUE TITLE
Is this still being actively developed and where could i find information about authoring the file format required

### ISSUE THREAD

**Issue by mmiscool** [vygr/JS-PCB#1]
Hello,

I have been writing a javascript schematic capture tool and found your project. 

I was hoping that there might be a way to get more information on the file format required for the input to your tool and the minimum information required to make it work. I think it would be possible to use this project as the routing engine in my own.

**Comment by vygr** [comment]
The format it takes is DSN or rather it converts standard DSN files to an internal format for faster routing. 

I had to reverse engineer the DSN format. :( guess at some parts of it. You may find official information online but I didn’t have much luck. 

The internal format I use is fairly simple and was based on my original Python PCB version. Check my other repos for the Python version as the readme has the details. 

Regards

Chris 

—————-
Chris Hinsley

**Comment by vygr** [comment]
Also the js-pcb readme file does cover the format of the internals that the DSN reader produces. 

—————-
Chris Hinsley

**Comment by RobertAditazz** [comment]
Hello,
I am evaluating different open source routers and found your work.  It looks very useful.
I see you have implemented routers in different languages.  Are they all at the same level
of development, or is one more developed than others?  Also, how may layers does your
router support?  What kind of routing algorithm are you using?  Thank you!
-Robert
